// userConstants.ts
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
 
export const DEFAULT_USER_ROLE = 'guest';
export const USER_SESSION_TIMEOUT = 3600; // in seconds
export const MAX_USER_LOGIN_ATTEMPTS = 5;
 
export const FETCH_TELEGRAM_USERS_REQUEST = 'FETCH_TELEGRAM_USERS_REQUEST';
export const FETCH_TELEGRAM_USERS_SUCCESS = 'FETCH_TELEGRAM_USERS_SUCCESS';
export const FETCH_TELEGRAM_USERS_FAILURE = 'FETCH_TELEGRAM_USERS_FAILURE';
export const RESET_TELEGRAM_USERS = 'RESET_TELEGRAM_USERS';
