export const SET_BOT_CONFIG = 'SET_BOT_CONFIG';
export const SET_CHANNEL_CONFIG = 'SET_CHANNEL_CONFIG';
export const RESET_CONFIG = 'RESET_CONFIG';

// Async Action Types
export const FETCH_BOT_CONFIG_REQUEST = 'FETCH_BOT_CONFIG_REQUEST';
export const FETCH_BOT_CONFIG_SUCCESS = 'FETCH_BOT_CONFIG_SUCCESS';
export const FETCH_BOT_CONFIG_FAILURE = 'FETCH_BOT_CONFIG_FAILURE';

export const FETCH_CHANNEL_CONFIG_REQUEST = 'FETCH_CHANNEL_CONFIG_REQUEST';
export const FETCH_CHANNEL_CONFIG_SUCCESS = 'FETCH_CHANNEL_CONFIG_SUCCESS';
export const FETCH_CHANNEL_CONFIG_FAILURE = 'FETCH_CHANNEL_CONFIG_FAILURE';
// constants.ts

export const PUT_BOT_CONFIG_REQUEST = "PUT_BOT_CONFIG_REQUEST";
export const PUT_BOT_CONFIG_SUCCESS = "PUT_BOT_CONFIG_SUCCESS";
export const PUT_BOT_CONFIG_FAILURE = "PUT_BOT_CONFIG_FAILURE";

export const DELETE_BOT_CONFIG_REQUEST = "DELETE_BOT_CONFIG_REQUEST";
export const DELETE_BOT_CONFIG_SUCCESS = "DELETE_BOT_CONFIG_SUCCESS";
export const DELETE_BOT_CONFIG_FAILURE = "DELETE_BOT_CONFIG_FAILURE";

export const PUT_CHANNEL_CONFIG_REQUEST = "PUT_CHANNEL_CONFIG_REQUEST";
export const PUT_CHANNEL_CONFIG_SUCCESS = "PUT_CHANNEL_CONFIG_SUCCESS";
export const PUT_CHANNEL_CONFIG_FAILURE = "PUT_CHANNEL_CONFIG_FAILURE";

export const DELETE_CHANNEL_CONFIG_REQUEST = "DELETE_CHANNEL_CONFIG_REQUEST";
export const DELETE_CHANNEL_CONFIG_SUCCESS = "DELETE_CHANNEL_CONFIG_SUCCESS";
export const DELETE_CHANNEL_CONFIG_FAILURE = "DELETE_CHANNEL_CONFIG_FAILURE";
export const FETCH_TELEGRAM_USERS_REQUEST = 'FETCH_TELEGRAM_USERS_REQUEST';
export const FETCH_TELEGRAM_USERS_SUCCESS = 'FETCH_TELEGRAM_USERS_SUCCESS';
export const FETCH_TELEGRAM_USERS_FAILURE = 'FETCH_TELEGRAM_USERS_FAILURE';
export const RESET_TELEGRAM_USERS = 'RESET_TELEGRAM_USERS';