export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNIN_REQUEST_USER = 'SIGNIN_REQUEST_USER';
export const LOGOUT = 'LOGOUT';

export const PASSWORD_CHANGE_REQUEST = 'PASSWORD_CHANGE_REQUEST';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAILURE = 'PASSWORD_CHANGE_FAILURE';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';

export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

export const TWO_FACTOR_AUTH_VERIFY_REQUEST = 'TWO_FACTOR_AUTH_VERIFY_REQUEST';
export const TWO_FACTOR_AUTH_VERIFY_SUCCESS = 'TWO_FACTOR_AUTH_VERIFY_SUCCESS';
export const TWO_FACTOR_AUTH_VERIFY_FAILURE = 'TWO_FACTOR_AUTH_VERIFY_FAILURE';

export const REQUEST_ERROR = 'REQUEST_ERROR';